import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "@/components/conditional";
import ConditionalBottomNav from "@/components/conditional-bottom";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // pilih sesuai kebutuhan
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${poppins.className} antialiased`}>
        <ConditionalNavbar />
        {children}
        <ConditionalBottomNav />
      </body>
    </html>
  );
}
