import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "@/components/conditional";
import ConditionalBottomNav from "@/components/conditional-bottom";

import EmployeeSidebar from "./(routes)/components/organisms/employer-sidebar";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // pilih sesuai kebutuhan
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="flex-1 flex flex-col">
          {/* Navbar tetap di atas */}
          <ConditionalNavbar />

          <div className="flex flex-1">
            {/* Sidebar muncul di samping konten, tapi di bawah navbar */}
            <EmployeeSidebar />

            {/* Konten utama */}
            <main className="flex-1 ">{children}</main>
             <Toaster />
          </div>
          <div className="hidden">  
          <ConditionalBottomNav />
          </div>
        </div>
      </body>
    </html>
  );
}
